@startuml
hide circle
skinparam linetype ortho

entity CheckStandard {
    * StandardID: text <Generated>
    --
    * Code: text <FK>
    WorkID: text <FK>
    * Purpose: text
    Method: text
    * ResultType: text
    * Subject: text
    * Description: textarea
    FormerCode: text <FK>
    FormerQuantity: number
    LatterCode: text <FK>
    LatterQuantity: number
    Cycle: number
    * Outsource: number
    * WorkerNumber: number
    * WorkingTime: float
    AdditonalCost: float
    Unit: text
    NormalRangeLow: float
    NormalRangeHigh: float
    KeyboardType: text
    StartPeriod: Date
    EndPeriod: Date
    Notes: textarea
}
' Method: Cleaning/ Visual check/ Listening check/ Touching check/ Measurement/ Recording/ Replacement/ Confirmation
' ResultType: Check/ Measure/ TakePicture/ Upload/ Replace/ Apply/ Propose 
entity CheckTool {
    * StandardID: text <FK>
    * ToolID: text <FK>
}
entity SupportDoc {
    * StandardID: text <FK>
    * DocumentID: text <FK>
}
entity Equipment {
    * Code: text <PK>
    --
    * Name: text
    * Category: text
    * Maker: text
    Image: image
    SymbolMark: image
    * Price: float
    Notes: textarea
}
' Category: Camera/ Recorder/ Periferals/ Panel/ Display/ Sensor/ Mount/ Output/ Communicator/ Power supply/ Battery
entity Work{
    * Subject: text
    --
    * Description: textarea
    * Purpose: text
    * Method: text
    Notes: text
}
' Purpose: Cleaning/ Function check/ Performance test/ Safety check/ Environment check/ Prevention measures/ Prevention measures/ Normalization/ Operation check
' add Campaign and special check
entity Tool {
    * Name: text
    --
    ToolType: text
    Description: textarea
    Image: image
    Notes: textarea
}
' ToolType: Indivisual tool/ Shared tool/ Purchaising/ Rental
entity Document {
    * Subject: text
    --
    * DocumentType: text
    URL: text
    notes: text
}
' DocumentType: Manual/ Instructions/ Checklist/ Contract/ Appearance/ Drawing

Equipment ||--o{ CheckStandard
Tool ||-d-|| CheckTool
CheckTool }o-r-o| CheckStandard
Document ||-d-o{ SupportDoc
SupportDoc }o-l-o| CheckStandard
CheckStandard }|--|{ Work
@enduml