@startuml
hide circle
skinparam linetype ortho

entity ContractInfo {
    * ContractCode: text <FK>
    --
    * EstimateCode: text <FK>
    * ContractID: text <FK>
    * SiteID: text <FK>
    * MonthlyFee: number
    * ContractPeriod: number
    * AutoRenewal: bool
    * RenewalPeriod: number
    * ContractLimitMonth: number
    * ContractDate: Date
    * StartDate: Date
    * Status: text
    * OncallTimes: number
    * ExpendableReplacement: bool
    * FiniteLifeItemReplacement: bool
    * FailureItemReplacement: bool
    * Outsource: bool
    TransportationFee: number
    AccomodationFee: number
    Notes: textarea
    Attention: textarea
}
' BuildingType: Office/ Factory/ Warehouse/ House/ Apartment/ Office building/ Store/ .. 

entity ContractEvent {
    * EventID: text <Generated>
    --
    * EventType: text
    * ContractCode: text <FK>
    InformedBy: text <FK>
    NotifyTo: text <FK>
    Notes: textarea
    EndDate: Date
    DueDate: Date
}
' EventType: Generated/ ChangeCondition/ Suspension/ Resume/ Termination

entity TargetContract {
    * ContractCode: text <FK>
    --
    System: text
    ContractDate: Date
    StartDate: Date
    Status: Text
}
' It's for demo, actually use CMS of each company.

entity TargetContractEquipment {
    * EquipmentID: text <Generated>
    --
    * Code: text <FK>
    * Quantity: number
    * Contractcode: text <FK>
    * Place: text
    * Height: text
    Notes: textArea
    Attention: textArea
}
' Height: Normal height/ Airial work platform/ Airial Work vehicle

entity PeriodicMaintenance {
    * PeriodicMaintenanceID: text <Generated>
    --
    * Name: text
    * ContractCode: text <FK>
    * Cycle: number
    * StartMonth: number
    * ServiceCleaning: bool
    * ServiceFunctionCheck: bool
    * ServicePerformanceTest: bool
    * ServiceSafetyCheck: bool
    * ServiceEnvironmentCheck: bool
    AdditionalWork: text <FK>
    Notes: textarea
}
' AdditionalWork: array of CheckStandardID

entity Equipment {
    * Code: text
}

entity HumanResource {
    * ResourceID: text <Generated>
    --
    * Name: text
    Address: text
}

HumanResource }|--|| ContractInfo
TargetContract ||-d-o{ TargetContractEquipment
Equipment ||-u-|{ TargetContractEquipment
TargetContractEquipment }o-r-|| ContractInfo
ContractInfo |o-r-o{ PeriodicMaintenance
ContractInfo ||--|{ ContractEvent

@enduml