@startuml
hide circle
skinparam linetype ortho

entity ContractInfo {
    * ContractCode: text <FK>
    --
    * EstimateCode: text <FK>
    * SiteName: text
    * SiteAddress: text
    LocationData: text
    * BuildingType: text
    * MonthlyFee: number
    * ContractPeriod: number
    * AutoRenewal: number
    * RenewalPeriod: number
    * ContractLimitMonth: number
    * ContractDate: Date
    * StartDate: Date
    SuspensionDate: Date
    SuspensionReason: textarea
    ResumeDate: Date
    EndDate: Date
    EndReason: textarea
    * OncallTimes: number
    * ExpendableReplacement: number
    * FiniteLifeItemReplacement: number
    * FailureItemReplacement: number
    * Outsource: number
    TransportationFee: number
    AccomodationFee: number
    Notes: textarea
    Attention: textarea
}
' BuildingType: Office/ Factory/ Warehouse/ House/ Apartment/ Office building/ Store/ .. 
entity TargetContract {
    * ContractCode: text <FK>
    --
    System: text
    ContractDate: Date
    StartDate: Date
    Status: Text
}
' for demo, actually use CMS of each company.
entity TargetContractEquipment {
    * EquipmentID: text <Generated>
    --
    * Code: text <FK>
    * Quantity: number
    * Contractcode: text <FK>
    * Place: text
    * Height: text
    Notes: textArea
    Attention: textArea
}
' Height: Normal height/ Airial work platform/ Airial Work vehicle
entity ContractPeriodicMaintenance {
    * PeriodicMaintenanceID: text <Generated>
    --
    * ContractCode: text <FK>
    * Name: text
    * Cycle: number
    * StartMonth: number
    * ServiceCleaning: number
    * ServiceFunctionCheck: number
    * ServicePerformanceTest: number
    * ServiceSafetyCheck: number
    * ServiceEnvironmentCheck: number
    AdditionalWork: text <FK>
    Notes: textarea
}
' AdditionalWork: array of CheckStandardID
entity Mst_Equipment {
    * Code: text
}
entity ContactPerson {
    * ContactID: text <Generated>
    --
    ContractCode: text <FK>
    * Name: text
    * ContactType: text
    CompanyID: text <FK>
    Department: text
    Title: text
    Tel: text
    Email text
    SMS: text
    Notes: textarea
    Attention: textarea
}
' ContactType: Contract/ Emergency/ Appointment/ Habitant/ Security/ Employee
entity Company {
    * CompanyID: text <Generated>
    --
    * Name: text
    * Address :text
    Tel: text
    Notes: textarea
}

ContractInfo ||--o{ TargetContractEquipment
ContractInfo ||--o| Mst_Company
ContractInfo |o--o{ ContractPeriodicMaintenance
ContractInfo ||--|{ ContactPerson
TargetContract ||--o{ TargetContractEquipment
TargetContractEquipment ||--|| Mst_Equipment
@enduml