@startuml
hide circle
skinparam linetype ortho

entity CheckStandard {
    * StandardID: text <Generated>
    --
    * Code: text <FK>
    ActionID: text <FK>
    * Purpose: text
    Method: text
    * CheckType: text
    * Subject: text
    * Description: textarea
    FormerCode: text <FK>
    FormerQuantity: number
    LatterCode: text <FK>
    LatterQuantity: number
    Cycle: number
    * Outsource: number
    * WorkerNumber: number
    * WorkingTime: Float
    AdditonalCost: number
    Unit: text
    NormalRangeLow: Float
    NormalRangeHigh: Float
    KeyboardType: text
    StartPeriod: Date
    EndPeriod: Date
    Notes: textarea
}
' Method: Cleaning/ Visual check/ Listening check/ Touching check/ Measurement/ Recording/ Replacement
' Type: Check/ Measure/ Picture/ Upload/ Replacement
entity CheckTool {
    * StandardID: text <FK>
    * ToolID: text <FK>
}
entity CheckSupportDoc {
    * StandardID: text <FK>
    * DocumentID: text <FK>
}
entity Mst_Equipment {
    * Code: text <PK>
    --
    * Name: text
    * Category: text
    Image: image
    Price: number
    Notes: text
}
' Category: Camera/ Recorder/ Periferals/ Panel/ Display/ Sensor/ Mount/ Output/ Communicator/ Power supply/ Battery
entity Actions{
    * ActionID: text <Generated>
    --
    * Subject: text
    * Description: textarea
    * Purpose: text
    * Method: text
    * ActionType: text
    Notes: text
}
' ActionType: Equipment/ Contract/ Operation/ Environment/ Others
entity Mst_Tools {
    * ToolID: text <Generated>
    --
    * Name: text
    ToolType: text
    Description: textarea
    Image: image
    Notes: textarea
}
' ToolType: Indivisual tool/ Shared tool/ Purchaising/ Rental
entity Mst_Documents {
    * DocumentID: text <Generated>
    --
    * Subject: text
    * DocumentType: text
    * URL: text
    notes: text
}
' DocumentType: Manual/ Instructions/ Checklist/ Contract/ Appearance/ Drawing
entity Mst_Purpose {
    * Name: text
    --
    Description: textarea
    Priority: number
}
' Purpose: Cleaning/ Function check/ Performance test/ Safety check/ Environment check/ Prevention measures/ Repair
' add Campaign and special check
CheckStandard |o--o{ Mst_Equipment
CheckStandard |o--o{ CheckTool
CheckStandard |o--o{ CheckSupportDoc
CheckTool ||--o{ Mst_Tools
CheckSupportDoc ||--o{ Mst_Documents
CheckStandard }|--|{ Mst_Actions
Mst_Actions ||--|| Mst_Purpose
@enduml