@startuml
hide circle
skinparam linetype ortho

entity EstimateBase {
    Name: text
    --
    Value: text
    --
    AdministrativeExpenses: float
    CostRate: float
    FailureRate: float
    TravelTimeInSite: number
    UnitCostSubcon: number
    UnitCostTechnician: number
    WorkingHoursPerDay: number
    AirialWorkPlatformTime: number
    AirialWorkPlatformCost: number
    AirialWorkVehicleTime: number
    AirialWorkVehicleCost: number
    DefaultAlarmPeriodicMaintenance: text <FK>
    DefaultSalePeriodicMaintenance: text <FK>
}
' use key-value model because calculation method is different.

entity EstimateInfo {
    * EstimateID: text <Generated>
    --
    * SiteID: text
    * ContractPeriod: number
    * AutoRenewal: bool
    * RenewalPeriod: number
    * ContractLimitMonth: number
    * OncallTimes: number
    * ExpendableReplacement: bool
    * FiniteLifeItemReplacement: bool
    * FailureItemReplacement: bool
    * Outsource: bool
    TransportationFee: number
    AccomodationFee: number
    Notes: textarea
    Attention: textarea
}

entity TargetContract {
    * ContractCode: text <FK>
    --
    System: text
    ContractDate: Date
    StartDate: Date
    Status: Text
}
' It's for demo, actually use CMS of each company.

entity EstTargetContractEquipment {
    * EquipmentID: text <Generated>
    --
    * Code: text <FK>
    * Quantity: number
    * ContractCode: text <FK>
    * Place: text
    * Height: text
    Notes: textArea
    Attention: textArea
}
' ContractCode can be set estimate code also.
' Height: Normal height/ Airial work platform/ Airial Work vehicle

entity EstPeriodicMaintenance {
   * PeriodicMaintenanceID: text <Generated>
    --
    * Name: text
    * ContractCode: text <FK>
    * Cycle: number
    * StartMonth: number
    * ServiceCleaning: bool
    * ServiceFunctionCheck: bool
    * ServicePerformanceTest: bool
    * ServiceSafetyCheck: bool
    * ServiceEnvironmentCheck: bool
    AdditionalWork: text <FK>
    Notes: textarea
}

entity Equipment {
    * Code: text
    --
    Name: text
}

entity HumanResource {
    * ResourceID: text <FK>
    --
    * Name: text
}

entity EstQuotation {
    * EstimateCode: text <Generated>
    --
    * EstimateID: text <FK>
    * CreationDate: Date
    * SubmitTo: text
    * SubmitFrom: text
    * OriginalMonthlyFee: number
    DiscountType: text
    DiscountValue: float
    DiscountReason: textarea
    * ProposeMonthlyFee: number
    * Details: textarea
    * TermsConditions: textarea
    Notes: textarea
    ApprovedDate: Date
    ApprovedBy: text <FK>
}
' DiscountType: Percentage/ Fixed fee/

entity TermsConditions {
    * Subject: text
    --
    * Description: textarea
    * Default: number
    * Order: number 
    Notes: textarea
}

Equipment }|-d-|{ EstTargetContractEquipment
HumanResource }o--|| EstimateInfo
EstimateInfo ||-l-|{ TargetContract
EstTargetContractEquipment }|--|| TargetContract
EstimateInfo ||--o{ EstPeriodicMaintenance
TermsConditions }o--|| EstQuotation
EstimateInfo ||-r-o{ EstQuotation

@enduml