@startuml
hide circle
skinparam linetype ortho

entity EstimateBase {
    Name: text
    --
    AdministrativeExpenses: float
    CostRate: float
    FailureRate: float
    TravelTimeInSite: number
    UnitCostSubcon: number
    UnitCostTechnician: number
    WorkingHoursPerDay: number
    AirialWorkPlatformTime: number
    AirialWorkPlatformCost: number
    AirialWorkVehicleTime: number
    AirialWorkVehicleCost: number
}
entity EstimateInfo {
    * EstimateID: text <Generated>
    --
    * SiteName: text
    * SiteAddress: text
    * BuildingType: text
    * ContractPeriod: number
    * AutoRenewal: number
    * ContractLimitMonth: number
    * OncallTimesPerYear: number
    * ExpendableReplacement: number
    * FiniteLifeItemReplacement: number
    * FailureItemReplacement: number
    * Outsource: number
    TransportationFee: number
    AccomodationFee: number
    Notes: textarea
    Attention: textarea
}
' EstimateID=1: Default setting
entity TargetContract {
    * ContractCode: text <FK>
    --
    System: text
    ContractDate: Date
    StartDate: Date
    Status: Text
}
' for demo, actually use CMS of each company.
entity EstTargetContractEquipment {
    * EquipmentID: text <Generated>
    --
    * Code: text <FK>
    * Quantity: number
    * Contractcode: text <FK>
    * Place: text
    * Height: text
    Notes: textArea
    Attention: textArea
}
entity EstPeriodicMaintenance {
    * PeriodicMaintenanceID: text <Generated>
    --
    * ContractCode: text <FK>
    * Name: text
    * Cycle: number
    * StartMonth: number
    * ServiceCleaning: number
    * ServiceFunctionCheck: number
    * ServicePerformanceTest: number
    * ServiceSafetyCheck: number
    * ServiceEnvironmentCheck: number
    AdditionalWork: text <FK>
    Notes: textarea
}
' PeriodicMaintenanceID=1: Default setting
entity Equipment {
    * Code: text
    --
    Name: text
}
entity ContactPerson {
    * ContactID: text <Generated>
    --
    ContractCode: text <FK>
    * Name: text
    * ContactType: text
    CompanyID: text <FK>
    Department: text
    Title: text
    Tel: text
    Email text
    SMS: text
    Notes: textarea
    Attention: textarea
}
entity Company {
    * Name: text
    --
    * Address :text
    Tel: text
    Notes: textarea
}
entity EstQuotation {
    * EstimateCode: text <Generated>
    --
    * EstimateID: text <FK>
    * CreationDate: Date
    * SubmitTo: text
    * SubmitFrom: text
    * OriginalMonthlyFee: number
    DiscountType: text
    DiscountValue: float
    DiscountReason: textarea
    * ProposeMonthlyFee: number
    * Details: textarea
    * TermsConditions: textarea
    Notes: textarea
    ApprovedDate: Date
    ApprovedBy: text <FK>
}
' DiscountType: Percentage/ Fixed fee/
entity TermsConditions {
    * Subject: text
    --
    * Description: textarea
    * Default: number
    * Order: number 
    Notes: textarea
}

EstimateInfo ||--o{ EstTargetContractEquipment
EstimateInfo ||--o| Company
EstimateInfo |o--o{ EstPeriodicMaintenance
EstimateInfo ||--|{ EstContactPerson
EstTargetContract ||--o{ EstTargetContractEquipment
EstTargetContractEquipment ||--|| Equipment
EstQuotation }o--|| EstimateInfo
EstQuotation ||--o{ TermsConditions
@enduml