@startuml
hide circle
skinparam linetype ortho

entity ContractPeriodicMaintenance {
    * PeriodicMaintenanceID: text
    --
    Cycle: number
    StartMonth: number
}
entity MaintenanceInfo {
    * MaintenanceID: text <Generated>
    --
    * ContractCode: text <FK>
    * PeriodicMaintenanceID: text <FK>
    * PediodicMaintenanceName: text
    * WorkingTime: number
    * WorkerNumber: number
    * Tools: text
    * HighPlaceWork: text
    * Outsource: number
    * ScheduledDate: Date
    AppointDate: Date
    AppointeTo: text
    AssignedTeamID: text <FK>
    Notes: textarea
    Attentions: textarea
}
' Status: Appointment/ assignment/ ScheduleFixed/ Pending/ Complete/ RemainingWork
entity MaintenanceEvent {
    * EventID: text <Generated>
    --
    * EventType: text
    * MaintenanceID: text <FK>
    InformedBy: text <FK>
    NotifyTo: text <FK>
    Notification: text
    Notes: textarea
    EndDate: Date
    DueDate: Date
}
' EventType: Generated/ Appoint/ Assign/ FixSchedule/ StartPM/ SubmitQtn
entity MaintenanceChecklist {
    * ChecklistID: text <Generated>
    --
    * MaintenanceID: text <FK> 
    * EquipmentID: text <FK>
    * StandardID: text <FK>
    * WorkingTime: number
    * WorkerNumber: number
    * HighPlaceWork: text
    * Tools: text
    Notes: textarea
    Attentions: textarea
}
entity PeriodicMaintenanceRecord {
    * ChecklistID: text <FK>
    --
    ReportedBy: text <FK>
    ResultText: text
    ResultImage: image
    ResultFile: binary
    Result: text
    Notes: textArea
    StartDate: Date
    EndDate: Date
    RecStartDate: Date
    RecStartLocation: text
    RecEndDate: Date
    RecEndLocation: text
    Duration: number
}
entity MaintenanceTeam {
    * TeamID: text <Generated>
    --
    * PersonnelID: text <FK>
    Leader: number
}
entity Personnel {
    * PersonnelID: text <Generated>
    --
    * Name: text
    Branch: text
    Department: text
    Title: text
    SubconID: text <FK>
    Tel: text
    Email: text
    SMS: text
    Notes: textarea
}
entity Subcontractor {
    * SubconID: text <Generated>
    --
    * Company: text
    Tel: text
    Email: text
    SMS: text
    Notes: textarea
}
entity Qualification {
    * QualificationName: text <FK>
    --
    * PersonnelID: text <FK>
    Expiration: Date
}

entity Mst_Qualification {
    * Name: text
    --
    Description: textarea
    Notes: textarea
}
entity ServiceArea {
    * City: text
    --
    * Type: text
    Branch: text <FK>
    Department: text <FK>
    PersonnelID: text <FK>
    Notes: textarea
}
' Type: Branch/ Department/ Company/ PersonnelID

ContractPeriodicMaintenance ||--|{ MaintenanceInfo
MaintenanceInfo ||--|{ MaintenanceChecklist
PeriodicMaintenanceRecord ||--|| MaintenanceChecklist
MaintenanceInfo ||--o{ MaintenanceEvent
MaintenanceInfo ||--|| MaintenanceTeam
MaintenanceTeam }|--o{ Personnel
Personnel ||--o| Subcontractor
Personnel }o--o{ Qualification
Qualification }o--o{ Mst_Qualification
Personnel }o--o{ ServiceArea
Subcontractor }o--o{ ServiceArea
@enduml