@startuml
hide circle
skinparam linetype ortho

entity PeriodicMaintenance {
    * PeriodicMaintenanceID: text
    --
    Cycle: number
    StartMonth: number
}

entity MaintenanceInfo {
    * MaintenanceID: text <Generated>
    --
    * ContractCode: text <FK>
    * PeriodicMaintenanceID: text <FK>
    * PediodicMaintenanceName: text
    * WorkingTime: number
    * WorkerNumber: number
    * HighPlaceWork: text
    * Outsource: number
    * ScheduledDate: Date
    CheckTool: text <FK>
    AppointmentDate: Date
    AppointmentTo: text
    AssignedTeamID: text <FK>
    Status: text
    Notes: textarea
    Attention: textarea
}
' Status: Appointment/ assignment/ ScheduleFixed/ Pending/ Complete/ RemainingWork

entity MaintenanceEvent {
    * EventID: text <Generated>
    --
    * EventType: text
    * MaintenanceID: text <FK>
    InformedBy: text <FK>
    NotifyTo: text <FK>
    Notes: textarea
    EndDate: Date
    DueDate: Date
}
' EventType: Generated/ Appoint/ Assign/ FixSchedule/ StartPM/ SubmitQtn

entity MaintenanceChecklist {
    * ChecklistID: text <Generated>
    --
    * MaintenanceID: text <FK> 
    EquipmentID: text <FK>
    * StandardID: text <FK>
    * WorkingTime: number
    * WorkerNumber: number
    * HighPlaceWork: text
    Tools: text
    Notes: textarea
    Attention: textarea
}

entity PeriodicMaintenanceRecord {
    * ChecklistID: text <FK>
    --
    ReportedBy: text <FK>
    ResultFlag: number
    ResultImage: image
    ResultFile: binary
    ResultType: text
    Report: textarea
    Notes: textArea
    StartDate: Date
    EndDate: Date
    RecStartDate: Date
    RecStartLocation: text
    RecEndDate: Date
    RecEndLocation: text
    Duration: number
}
' ResultType: Completed/ Pending/ RemainingWork

entity MaintenanceTeam {
    * TeamID: text <Generated>
    --
    * ResourceID: text <FK>
    Leader: bool
    Notes: textarea
}

entity HumanResource {
    * ResourceID: text <Generated>
    --
    * Name: text
    * ResourceType: text
    Address: text
    LocationData: text
    Telephone1: text
    Telephone2: text
    Email: text
    SMS: text
    Notes: textarea
}
' ResourceType: Group/ Individual

entity Relationship {
    * ResourceID: text <FK>
    * RelationshipWith: text <FK>
    * RelationshipType; text
    Notes: textarea
}

entity Qualification {
    * QualificationName: text <FK>
    * ResourceID: text <FK>
    Expiration: Date
    Notes: textarea
}

entity Mst_Qualification {
    * Name: text
    --
    Description: textarea
    Notes: textarea
}

entity ServiceArea {
    * ResourceID: text <FK>
    * City: text
    Notes: textarea
}

PeriodicMaintenance }o-r-|| MaintenanceInfo
MaintenanceInfo ||-r-|{ MaintenanceChecklist
MaintenanceChecklist ||-u-|| PeriodicMaintenanceRecord
MaintenanceInfo ||--o{ MaintenanceEvent
Relationship }|--|| HumanResource
ServiceArea }o-l-|| HumanResource
HumanResource }|-d-|{ MaintenanceTeam
Mst_Qualification }|--|| Qualification
Qualification }o-r-|| HumanResource
MaintenanceTeam ||--|| MaintenanceInfo

@enduml