@startuml
hide circle
skinparam linetype ortho

entity MaintenanceSchedule {
    * ID: text <Generated>
    --
    * ContractCode: text <FK>
    * MaintenanceID: text <FK>
    * ScheduledDate: Date
    * MaintenanceName: text
    * WorkingTime: number
    * WorkerNumber: number
    * HighPlaceWork: text
    * Outsource: number
    AppointmentDate: Date
    AppointmentPerson: text
    ScheduledDate: Date
    AssignedEmployeeID: text <FK>
    AssignedSubcontractorID: text <FK>
    FixedSchedule: Date
    Status: text
    Notes: textarea
    Attentions: textarea
}
' Status: Appointment/ assignment/ ScheduleFixed/ Pending/ Complete/ RemainingWork
entity Maintenancechecklist {
    * ID: text <Generated>
    --
    * ScheduleID: text <FK> 
    * StandardID: text <FK>
    * EquipmentID: text <FK>
    Notes: textarea
    Attentions: textarea
}
entity MaintenanceRecord {
    * ChecklistID: text <FK>
    --
    * Code: text <FK>
    * Quantity: number
    * Contractcode: text <FK>
    * Place: text
    * Height: text
    Notes: textArea
    Attentions: textArea
}


Contract ||--o{ TargetContractEquipment
Contract |o--o{ PeriodicMaintenance
Contract ||--o| Mst_Company
Contract ||--o| Mst_Person
@enduml