@startuml
hide circle
skinparam linetype ortho

entity ContractPeriodicMaintenance {
    * ID: text
    --
    Cycle: number
    StartMonth: number
}
entity MaintenanceSchedule {
    * ID: text <Generated>
    --
    * ContractCode: text <FK>
    * MaintenanceID: text <FK>
    * ScheduledDate: Date
    * MaintenanceName: text
    * WorkingTime: number
    * WorkerNumber: number
    * HighPlaceWork: text
    * Outsource: number
    AppointmentDate: Date
    AppointmentPerson: text
    ScheduledDate: Date
    AssignedEmployeeID: text <FK>
    AssignedSubcontractorID: text <FK>
    FixedSchedule: Date
    Status: text
    Notes: textarea
    Attentions: textarea
}
' Status: Appointment/ assignment/ ScheduleFixed/ Pending/ Complete/ RemainingWork
entity MaintenanceChecklist {
    * ID: text <Generated>
    --
    * ScheduleID: text <FK> 
    * StandardID: text <FK>
    * EquipmentID: text <FK>
    Notes: textarea
    Attentions: textarea
}
entity MaintenanceRecord {
    * ChecklistID: text <FK>
    --
    ResultText: text
    ResultImage: image
    ResultFile: binary
    Result: text
    Notes: textArea
    Attentions: textArea
}

MaintenanceSchedule ||--|{ MaintenanceChecklist
MaintenanceChecklist ||--|| MaintenanceRecord
ContractPeriodicMaintenance ||--|{ MaintenanceSchedule
@enduml