@startuml
hide circle
skinparam linetype ortho

entity HumanResource {
    * ResourceID: GUID <Generated>
    --
    * Name: text
    Tel: text
    Email: text
}

entity Terminal {
    * TerminalID: GUID <Generated>
    --
    * Name: text
    * TerminalType: text
    Account: text <FK>
    tel: text
}
' TerminalType: iPhone/ Android phone/ iPad/ Android tablet 

entity TaskList {
    * TaskID: GUID <Generated>
    --
    * TaskType: text <FK>
    * SiteID: text <FK>
    * SiteName: text <FK>
    * SiteAddress: text <FK>
    * Subject: text
    * Content: textarea
    ResponseDate: date
    DueDate: date
    AssignedTo: text <FK>
    Status: text <FK>
}
' TaskType: EmergencyDispatch/ PeriodicMaintenance/ Troubleshooting/ Patrol/ Meeting
' Status: Created/ Assigned/ Ongoing/ Completed/ Pending/

entity Event {
    * EventID: GUID <Generated>
    --
    * TaskID: text <FK>
    * EventType: text <FK>
    NotifyFrom: text <FK>
    Notes: textarea
    UpdatedTo: date
    Location: text
}
' EventType: Initial/ UpdateContent/ UpdateTime/ Allocate/ Accept/ Reject/ ReportSuccess/ ReportFailue/ Pending/ PeriodicReport

entity Site {
    * SiteID: GUID <Generated>
    --
    ContractCode: text
    * Name: text
    * Address: text
    Notes: textarea
}

TaskList ||--|{ History

@enduml