@startuml

state 日本{
    state セコム日本{
        TSS事業推進本部 --> G国際事業本部: 要請事項
        G国際事業本部 --> TSS事業推進本部: 重要事項報告
    }
    株式会社森ビル --> TSS事業推進本部: 要請事項
    TSS事業推進本部 --> 株式会社森ビル: 重要事項報告
}
state インドネシア {
    セコムインドネシア --> セコムバイヤンカラ: 対応支援
    セコムバイヤンカラ --> セコムインドネシア: 事案共有
    state MoriTower {
        セコムバイヤンカラ --> 派遣隊: 指導育成、業務管理
        派遣隊 --> 森ビル現地法人: 常駐業務
        森ビル現地法人 --> 派遣隊: 要請、事案連絡
    }
}
セコムインドネシア --> MoriTower: 障害対応/支援
派遣隊 -u-> セコムバイヤンカラ: 事案報告
G国際事業本部 --> セコムインドネシア: 責任者派遣、指導管理
G国際事業本部 --> セコムバイヤンカラ: 責任者派遣、指導管理
セコムバイヤンカラ --> G国際事業本部: 重要事項報告
セコムバイヤンカラ --> 森ビル現地法人: 日本人対応
セコムインドネシア --> 森ビル現地法人: 日本人対応

@enduml