@startuml

[*] --> ScreenTop
ScreenTop --> ScreenMenu
ScreenMenu --> ScreenRegTool
ScreenMenu --> ScreenRegEquipmnent
ScreenMenu --> ScreenRegDocument
ScreenMenu --> ScreenRegWork
ScreenMenu --> ScreenRegCheckStandard
ScreenRegCheckStandard --> ScreenSelWork
ScreenRegCheckStandard --> ScreenSelTool
ScreenRegCheckStandard --> ScreenSelDocument

RegistrationMenu --> Estimate
state Estimate {
    [*] --> EstimateCondition
    [*] --> TermsCondition
    [*] --> MaintenanceCondition
}
RegistrationMenu --> Organization
state Organization {
    [*] --> Personnel
    [*] --> Subcontractor
    [*] --> Company
    [*] --> Qualification
    Personnel --> Company
    Personnel --> Qualification
    Subcontractor --> Company
    Subcontractor --> Personnel
}
' EquipmentData: EquipmentBase, CheckStandard, 
@enduml