@startuml

[*] --> TopMenu
TopMenu: Instructions
TopMenu: Information
TopMenu: ContractManagement
TopMenu: MaintenanceManagement
TopMenu: Statistics
TopMenu: Registration

TopMenu --> Registration: Click Icon
state Registration {
    [*] --> RegistrationMenu
    RegistrationMenu --> Equipment
    state Equipment {
        [*] --> EquipmentData
        [*] --> CheckStandard
        [*] --> Tool
        [*] --> Document
        CheckStandard --> Tool
        CheckStandard --> Document
    }
    RegistrationMenu --> Estimate
    state Estimate {
        [*] --> EstimateCondition
        [*] --> TermsCondition
        [*] --> MaintenanceCondition
    }
    RegistrationMenu --> Organization
    state Organization {
        [*] --> Personnel
        [*] --> Subcontractor
        [*] --> Company
        [*] --> Qualification
        Personnel --> Company
        Personnel --> Qualification
        Subcontractor --> Company
        Subcontractor --> Personnel
    }
}
Registration --> TopMenu: Back button
' EquipmentData: EquipmentBase, CheckStandard, 
@enduml